<?php

namespace FantasticBooksBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CharacterFromBookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterFromBookRepository extends EntityRepository
{
}
