<?php

namespace FantasticBooksBundle\Repository;

/**
 * Author_BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Author_BookRepository extends \Doctrine\ORM\EntityRepository
{
}
