<?php

namespace FantasticBooksBundle\Repository;

/**
 * Book_CharacterFromBookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Book_CharacterFromBookRepository extends \Doctrine\ORM\EntityRepository
{
}
